"""empty message

Revision ID: 653a608e9f03
Revises: 6e1dd7862f5a
Create Date: 2016-05-13 20:03:23.622158

"""

# revision identifiers, used by Alembic.
revision = '653a608e9f03'
down_revision = '6e1dd7862f5a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'user_id')
    ### end Alembic commands ###
