"""empty message

Revision ID: 7e0b1d2db635
Revises: c6db0f27200b
Create Date: 2016-05-14 13:42:46.584799

"""

# revision identifiers, used by Alembic.
revision = '7e0b1d2db635'
down_revision = 'c6db0f27200b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.add_column('order', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('order', 'reject_at')
    op.drop_column('order', 'phone_at')
    op.drop_column('order', 'sign_at')
    op.drop_column('order', 'sms_at')
    op.alter_column('user', 'mobile',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'mobile',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    op.add_column('order', sa.Column('sms_at', mysql.DATETIME(), nullable=True))
    op.add_column('order', sa.Column('sign_at', mysql.DATETIME(), nullable=True))
    op.add_column('order', sa.Column('phone_at', mysql.DATETIME(), nullable=True))
    op.add_column('order', sa.Column('reject_at', mysql.DATETIME(), nullable=True))
    op.drop_column('order', 'updated_at')
    op.drop_column('order', 'status')
    ### end Alembic commands ###
