"""empty message

Revision ID: bb25d55442b6
Revises: 94f1721247f1
Create Date: 2016-05-21 12:53:53.286413

"""

# revision identifiers, used by Alembic.
revision = 'bb25d55442b6'
down_revision = '94f1721247f1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('is_quick', sa.Boolean(), nullable=True))
    op.alter_column('user', 'mobile',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'mobile',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    op.drop_column('order', 'is_quick')
    ### end Alembic commands ###
