"""empty message

Revision ID: c6db0f27200b
Revises: eae11de38cb0
Create Date: 2016-05-13 22:19:25.902358

"""

# revision identifiers, used by Alembic.
revision = 'c6db0f27200b'
down_revision = 'eae11de38cb0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobile2', sa.String(length=11), nullable=True))
    op.alter_column('user', 'mobile',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True,
               existing_server_default=sa.text(u"''"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'mobile',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False,
               existing_server_default=sa.text(u"''"))
    op.drop_column('user', 'mobile2')
    ### end Alembic commands ###
