"""empty message

Revision ID: e104ca36d471
Revises: None
Create Date: 2016-05-10 23:47:34.732715

"""

# revision identifiers, used by Alembic.
revision = 'e104ca36d471'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_name', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('username')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_name', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_name', sa.DateTime(), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id', 'mobile')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_name', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('web_site', sa.String(length=250), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_store',
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], )
    )
    op.create_table('user_name',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_name', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_name', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('no', sa.SmallInteger(), nullable=True),
    sa.Column('remark', sa.String(length=500), nullable=True),
    sa.Column('plan_at', sa.DateTime(), nullable=True),
    sa.Column('phone_at', sa.DateTime(), nullable=True),
    sa.Column('sms_at', sa.DateTime(), nullable=True),
    sa.Column('sign_at', sa.DateTime(), nullable=True),
    sa.Column('reject_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='uix_1')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('user_name')
    op.drop_table('member_store')
    op.drop_table('company')
    op.drop_table('user')
    op.drop_table('store')
    op.drop_table('member')
    ### end Alembic commands ###
