"""empty message

Revision ID: eae11de38cb0
Revises: 653a608e9f03
Create Date: 2016-05-13 22:16:42.343737

"""

# revision identifiers, used by Alembic.
revision = 'eae11de38cb0'
down_revision = '653a608e9f03'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('store_id', sa.Integer(), nullable=True))
    op.alter_column('user', 'mobile',
               existing_type=mysql.VARCHAR(length=11),
               nullable=True)
    op.create_foreign_key(None, 'user', 'store', ['store_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.alter_column('user', 'mobile',
               existing_type=mysql.VARCHAR(length=11),
               nullable=False)
    op.drop_column('user', 'store_id')
    ### end Alembic commands ###
